<a href="https://colab.research.google.com/github/LuisSerranoCardoso/Universidad/blob/main/EstructuraDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase Pila

In [ ]:
class Stack:
    def __init__(self):
      self.items = []

    def push(self, item):
      self.items.append(item)

    def pop(self):
      if not self.is_empty():
         return self.items.pop()
      return None

    def peek (self):
       if not self.is_empty():
          return self.items[-1]
       return None

    def is_empty(self):
       return len(self.items)== 0

    def size(self):
        return len(self.items)

    def __str__(self):
      return f"Mi pila es {self.items[::-1]}"

stack = Stack()
stack.push(1)
stack.push(2)
stack.push(3)
print(stack.pop())
print(stack.peek())
print(stack.size())
print(stack.is_empty())
print(stack)


3
2
2
False
Mi pila es [2, 1]


Ejercicio Diccionario: estudiantes y notas

In [ ]:
#Crear un diccionario vacio

estudiantes = {}

#Bucle para introducir nombre y notas
while True:
    name = input("Introduzca nombre \"done\"  para terminar: ")
    if name.lower() == 'done':
      break

    grade = float(input("Introduzca nota: "))
    estudiantes[name] = grade

#Imprimir los estudiantes y sus notas

for name, grade in estudiantes.items():
    print(f"{name}: {grade}")

#Calcular la media
if estudiantes:
  average = sum(estudiantes.values())/len(estudiantes)
  print(f"La media es {average: .2f}")
else:
  print("No ha introducido estudiantes")


#Calcular la nota más alta
if estudiantes:
   max_nota = max(estudiantes.values())
   print(f"La nota más alta es {max_nota}")
else:
  print("No ha introducido estudiantes")


#Imprimir el nombre del estudiante(s) con la nota más alta
if estudiantes:
  top_estudiante = [name for name, grade in estudiantes.items() if grade == max_nota]
  print(f"El(los) estudiante(s) con la nota más alta es {top_estudiante}")



Introduzca nombre "done"  para terminar: ana
Introduzca nota: 8.9
Introduzca nombre "done"  para terminar: pepe
Introduzca nota: 5.6
Introduzca nombre "done"  para terminar: Mary
Introduzca nota: 7.3
Introduzca nombre "done"  para terminar: done
ana: 8.9
pepe: 5.6
Mary: 7.3
La media es  7.27
La nota más alta es 8.9
El(los) estudiante(s) con la nota más alta es ['ana']


Ejercicio de Gestor de tareas

In [ ]:
from enum import Enum, auto

class EstadoTareas(Enum):
    NOT_EMPEZADA = auto()
    IN_PROGRESO = auto()
    COMPLETADA = auto()
    BLOQUEADA = auto()

# Uso de imprimir Tareas
def imprimir_tareas(nombret, estado):
    if estado == EstadoTareas.NOT_EMPEZADA:
        print(f"The task '{nombret}' has not started yet.")
    elif estado == EstadoTareas.IN_PROGRESO:
        print(f"The task '{nombret}' is currently in progress.")
    elif estado == EstadoTareas.COMPLETADA:
        print(f"The task '{nombret}' is completed.")
    elif estado == EstadoTareas.BLOQUEADA:
        print(f"The task '{nombret}' is currently blocked.")

# Probar el ejemplo
imprimir_tareas("Correción exámenes",EstadoTareas.NOT_EMPEZADA)

The task 'Correción exámenes' has not started yet.


Arrays con Numpy

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d)

print(arr_2d[2,2])

arr_2d[1,1] = 20

print(arr_2d)

arr_2d= np.append(arr_2d, [[10, 11, 12]], axis=0)

print(arr_2d)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[ 1  2  3]
 [ 4 20  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 20  6]
 [ 7  8  9]
 [10 11 12]]


Inicialización

In [ ]:
import numpy as np

arr_2d = np.zeros((2,3))
print(arr_2d)

arr_2d = np.ones((3,3))
print(arr_2d)

arr_bool = np.array([1,2,3,4,5], dtype = float)
print(arr_bool)

arr1= np.arange(1,10,3)
print(arr1)

arr2 = np.linspace(0,10,3)
print(arr2)

type(arr2)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 2. 3. 4. 5.]
[1 4 7]
[ 0.  5. 10.]


numpy.ndarray

Propiedades

In [ ]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Get the dimensions of the array: (2, 3)
print(array_2d.shape)

# Get the length of the array: 2  (primera dimension, es decir filas)
print(len(array_2d))

# Get the number of dimensions of the array: 2 (ejes del array o dimensiones)
print(array_2d.ndim)

# Get the number of elements in the array: 6
print(array_2d.size)

# Get the data type of the array
print(array_2d.dtype)

# Get the type of the array
print(type(array_2d))

(2, 3)
2
2
6
int64
<class 'numpy.ndarray'>
